name: cmt action

on:
  schedule:
    - cron: '02 */2 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "cmt bot"
      
      - name: updating cmt
        run: python3 res/26-1/cmt.py > res/26-1/cmt.m3u8
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull origin main
          git commit -m "cmt updated"
          git push origin main
